EXTRACTION_BACKEND = "ollama"
RECONCILE_BACKEND = "ollama"
OLLAMA_HOST = "http://localhost:11434"
OLLAMA_VISION_MODEL = "qwen2.5vl:7b"
OLLAMA_TEXT_MODEL = "qwen2.5:7b"
RENDER_DPI = 150
RULES_MATCH_THRESHOLD = 0.28
TESSERACT_CMD = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
DETECTOR_WEIGHTS = "detector/runs/drawing_regions/weights/best.pt"
DETECTOR_CONF = 0.25
REGION_READ_BACKEND = "ollama"